server:
  port: 9991
  contextPath: /wechat-service
  address: 0.0.0.0

spring:
  profiles:
    active: uat
# ACTIVEMQ
  activemq:
    broker-url: ${activemq.broker-url}
    user: ${activemq.user}
    password: ${activemq.password}
    in-memory: true
    pool:
      enabled: false
    packages:
      trust-all: true
#JMS
  jms:
    pub-sub-domain: true

logging:
  level:
      root: error
      org.springframework.web: info
      org.apache.ibatis: error
      com.wuyuan: info
      com.ctrip.framework.apollo : info
      org.springframework.jms: debug
  path: "./logs"





